-- 코드를 입력하세요
SELECT FOOD_PRODUCT.PRODUCT_ID,FOOD_PRODUCT.PRODUCT_NAME,SUM(PRICE*AMOUNT)AS TOTAL_SALES
FROM FOOD_PRODUCT
JOIN FOOD_ORDER
WHERE FOOD_PRODUCT.PRODUCT_ID=FOOD_ORDER.PRODUCT_ID	
AND YEAR(PRODUCE_DATE)=2022 AND MONTH(PRODUCE_DATE)=05
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC,PRODUCT_ID;